name: Hellow world workflow
on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
jobs:
  helloworld:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        run: echo " Hello this is my actions speaking"
        shell: bash
